name: Release
on:
  push:
    tags:
      - v*
jobs:
  setup:
    name: 🛠 Setup
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: 📥 Install deps
        run: npm ci

      - name: 🌐 Install Playwright browser
        run: npx playwright install --with-deps chromium

      - name: 🔨 Build
        run: npm run build

      - name: 🗎 Generate PDF
        run: node ./scripts/make-pdf.mjs

      - name: 🚀 Create release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
